routes/web.php
<?php

use App\Http\Controllers\LanguageController;

/*
 * Global Routes
 * Routes that are used between both frontend and backend.
 */

// Switch between the included languages
Route::get('lang/{lang}', [LanguageController::class, 'swap']);

/*
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    include_route_files(__DIR__.'/frontend/');
});

/*
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    /*
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     * These routes can not be hit if the password is expired
     */
    include_route_files(__DIR__.'/backend/');
});

app/Models/Traits/Attribute/ThemeAttribute.php
<?php

namespace App\Models\Traits\Attribute;

use Illuminate\Support\Facades\Hash;

/**
 * Trait ThemeAttribute.
 */
trait ThemeAttribute
{
    /**
     * @return string
     */
    public function getShowButtonAttribute()
    {
        return '<a href="'.route('admin.themes.show', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.view').'" class="btn btn-info"><i class="fas fa-eye"></i></a>';
    }

    /**
     * @return string
     */
    public function getEditButtonAttribute()
    {
        return '<a href="'.route('admin.themes.edit', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.edit').'" class="btn btn-primary"><i class="fas fa-edit"></i></a>';
    }

    /**
     * @return string
     */
    public function getDeleteButtonAttribute()
    {
        return '<a href="'.route('admin.themes.destroy', $this).'"
                title="'.__('buttons.general.crud.delete').'"
                data-method="delete"
                data-trans-button-cancel="'.__('buttons.general.cancel').'"
                data-trans-button-confirm="'.__('buttons.general.crud.delete').'"
                data-trans-title="'.__('strings.backend.general.are_you_sure').'"
                class="btn btn-danger"><i class="fas fa-trash"></i></a> ';
    }

    /**
     * @return string
     */
    public function getDeletePermanentlyButtonAttribute()
    {
        return '<a href="'.route('admin.themes.delete-permanently', $this).'" name="confirm_item" class="btn btn-danger"><i class="fas fa-trash" data-toggle="tooltip" data-placement="top" title="'.__('buttons.backend.themes.delete_permanently').'"></i></a> ';
    }

    /**
     * @return string
     */
    public function getRestoreButtonAttribute()
    {
        return '<a href="'.route('admin.themes.restore', $this).'" name="confirm_item" class="btn btn-info"><i class="fas fa-sync" data-toggle="tooltip" data-placement="top" title="'.__('buttons.backend.themes.restore').'"></i></a> ';
    }

    /**
     * @return string
     */
    public function getActionButtonsAttribute()
    {
        return '
    	<div class="btn-group" role="group" aria-label="'.__('labels.backend.themes.actions').'">
		  '.$this->show_button.'
		  '.$this->edit_button.'
		  '.$this->delete_button.'
        </div>';
    }

    /**
     * @return string
     */
    public function getTrashedButtonsAttribute()
    {
        return '
            <div class="btn-group" role="group" aria-label="'.__('labels.backend.themes.actions').'">
                '.$this->restore_button.'
                '.$this->delete_permanently_button.'
            </div>';
    }

    /**
     * @return string
     */
    public function getFrontendShowButtonAttribute()
    {
        return '<a href="'.route('frontend.themes.show', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.view').'" class="btn btn-info"><i class="fas fa-eye"></i></a>';
    }

    /**
     * @return string
     */
    public function getFrontendEditButtonAttribute()
    {
        return '<a href="'.route('frontend.themes.edit', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.edit').'" class="btn btn-primary"><i class="fas fa-edit"></i></a>';
    }

    /**
     * @return string
     */
    public function getFrontendDeleteButtonAttribute()
    {
        return '<a href="'.route('frontend.themes.destroy', $this).'"
                title="'.__('buttons.general.crud.delete').'"
                data-method="delete"
                data-trans-button-cancel="'.__('buttons.general.cancel').'"
                data-trans-button-confirm="'.__('buttons.general.crud.delete').'"
                data-trans-title="'.__('strings.backend.general.are_you_sure').'"
                class="btn btn-danger"><i class="fas fa-trash"></i></a> ';
    }

    /**
     * @return string
     */
    public function getFrontendDeletePermanentlyButtonAttribute()
    {
        return '<a href="'.route('frontend.themes.delete-permanently', $this).'" name="confirm_item" class="btn btn-danger"><i class="fas fa-trash" data-toggle="tooltip" data-placement="top" title="'.__('buttons.backend.themes.delete_permanently').'"></i></a> ';
    }

    /**
     * @return string
     */
    public function getFrontendRestoreButtonAttribute()
    {
        return '<a href="'.route('frontend.themes.restore', $this).'" name="confirm_item" class="btn btn-info"><i class="fas fa-sync" data-toggle="tooltip" data-placement="top" title="'.__('buttons.backend.themes.restore').'"></i></a> ';
    }

    /**
     * @return string
     */
    public function getFrontendActionButtonsAttribute()
    {
        return '
    	<div class="btn-group" role="group" aria-label="'.__('labels.backend.themes.actions').'">
		  '.$this->frontend_show_button.'
		  '.$this->frontend_edit_button.'
		  '.$this->frontend_delete_button.'
        </div>';
    }

    /**
     * @return string
     */
    public function getFrontendTrashedButtonsAttribute()
    {
        return '
            <div class="btn-group" role="group" aria-label="'.__('labels.backend.themes.actions').'">
                '.$this->frontend_restore_button.'
                '.$this->frontend_delete_permanently_button.'
            </div>';
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

/**
 * Class DashboardController.
 */
class DashboardController extends Controller
{
    /**
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('backend.dashboard');
    }
}

app/Http/Controllers/Backend/PluginController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Exceptions\GeneralException;

use App\Models\Plugin;
use App\Repositories\Backend\PluginRepository;
use App\Http\Requests\Backend\Plugin\ManagePluginRequest;
use App\Http\Requests\Backend\Plugin\StorePluginRequest;
use App\Http\Requests\Backend\Plugin\UpdatePluginRequest;

use App\Events\Backend\Plugin\PluginCreated;
use App\Events\Backend\Plugin\PluginUpdated;
use App\Events\Backend\Plugin\PluginDeleted;

class PluginController extends Controller
{
    /**
     * @var PluginRepository
     */
    protected $pluginRepository;

    /**
     * PluginController constructor.
     *
     * @param PluginRepository $pluginRepository
     */
    public function __construct(PluginRepository $pluginRepository)
    {
        $this->pluginRepository = $pluginRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param ManagePluginRequest $request
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(ManagePluginRequest $request)
    {
        return view('backend.plugin.index')
            ->withplugins($this->pluginRepository->getActivePaginated(25, 'id', 'asc'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param ManagePluginRequest    $request
     *
     * @return mixed
     */
    public function create(ManagePluginRequest $request)
    {
        return view('backend.plugin.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StorePluginRequest $request
     *
     * @return mixed
     * @throws \Throwable
     */
    public function store(StorePluginRequest $request)
    {
        $this->pluginRepository->create($request->only(
            'title'
        ));

        // Fire create event (PluginCreated)
        event(new PluginCreated($request));

        return redirect()->route('admin.plugins.index')
            ->withFlashSuccess(__('backend_plugins.alerts.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param ManagePluginRequest  $request
     * @param Plugin               $plugin
     *
     * @return mixed
     */
    public function show(ManagePluginRequest $request, Plugin $plugin)
    {
        return view('backend.plugin.show')->withPlugin($plugin);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param ManagePluginRequest $request
     * @param Plugin              $plugin
     *
     * @return mixed
     */
    public function edit(ManagePluginRequest $request, Plugin $plugin)
    {
        return view('backend.plugin.edit')->withPlugin($plugin);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdatePluginRequest  $request
     * @param Plugin               $plugin
     *
     * @return mixed
     * @throws \App\Exceptions\GeneralException
     * @throws \Throwable
     */
    public function update(UpdatePluginRequest $request, Plugin $plugin)
    {
        $this->pluginRepository->update($plugin, $request->only(
            'title'
        ));

        // Fire update event (PluginUpdated)
        event(new PluginUpdated($request));

        return redirect()->route('admin.plugins.index')
            ->withFlashSuccess(__('backend_plugins.alerts.updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param ManagePluginRequest $request
     * @param Plugin              $plugin
     *
     * @return mixed
     * @throws \Exception
     */
    public function destroy(ManagePluginRequest $request, Plugin $plugin)
    {
        $this->pluginRepository->deleteById($plugin->id);

        // Fire delete event (PluginDeleted)
        event(new PluginDeleted($request));

        return redirect()->route('admin.plugins.deleted')
            ->withFlashSuccess(__('backend_plugins.alerts.deleted'));
    }

    /**
     * Permanently remove the specified resource from storage.
     *
     * @param ManagePluginRequest $request
     * @param Plugin              $deletedPlugin
     *
     * @return mixed
     * @throws \App\Exceptions\GeneralException
     * @throws \Throwable
     */
    public function delete(ManagePluginRequest $request, Plugin $deletedPlugin)
    {
        $this->pluginRepository->forceDelete($deletedPlugin);

        return redirect()->route('admin.plugins.deleted')
            ->withFlashSuccess(__('backend_plugins.alerts.deleted_permanently'));
    }

    /**
     * @param ManagePluginRequest $request
     * @param Plugin              $deletedPlugin
     *
     * @return mixed
     * @throws \App\Exceptions\GeneralException
     */
    public function restore(ManagePluginRequest $request, Plugin $deletedPlugin)
    {
        $this->pluginRepository->restore($deletedPlugin);

        return redirect()->route('admin.plugins.index')
            ->withFlashSuccess(__('backend_plugins.alerts.restored'));
    }

    /**
     * Display a listing of deleted items of the resource.
     *
     * @param ManagePluginRequest $request
     *
     * @return mixed
     */
    public function deleted(ManagePluginRequest $request)
    {
        return view('backend.plugin.deleted')
            ->withplugins($this->pluginRepository->getDeletedPaginated(25, 'id', 'asc'));
    }
}

app/Http/Controllers/Backend/ThemeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Exceptions\GeneralException;

use App\Models\Theme;
use App\Repositories\Backend\ThemeRepository;
use App\Http\Requests\Backend\Theme\ManageThemeRequest;
use App\Http\Requests\Backend\Theme\StoreThemeRequest;
use App\Http\Requests\Backend\Theme\UpdateThemeRequest;

use App\Events\Backend\Theme\ThemeCreated;
use App\Events\Backend\Theme\ThemeUpdated;
use App\Events\Backend\Theme\ThemeDeleted;

class ThemeController extends Controller
{
    /**
     * @var ThemeRepository
     */
    protected $themeRepository;

    /**
     * ThemeController constructor.
     *
     * @param ThemeRepository $themeRepository
     */
    public function __construct(ThemeRepository $themeRepository)
    {
        $this->themeRepository = $themeRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param ManageThemeRequest $request
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(ManageThemeRequest $request)
    {
        return view('backend.theme.index')
            ->withthemes($this->themeRepository->getActivePaginated(25, 'id', 'asc'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param ManageThemeRequest    $request
     *
     * @return mixed
     */
    public function create(ManageThemeRequest $request)
    {
        return view('backend.theme.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreThemeRequest $request
     *
     * @return mixed
     * @throws \Throwable
     */
    public function store(StoreThemeRequest $request)
    {
        $this->themeRepository->create($request->only(
            'title'
        ));

        // Fire create event (ThemeCreated)
        event(new ThemeCreated($request));

        return redirect()->route('admin.themes.index')
            ->withFlashSuccess(__('backend_themes.alerts.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param ManageThemeRequest  $request
     * @param Theme               $theme
     *
     * @return mixed
     */
    public function show(ManageThemeRequest $request, Theme $theme)
    {
        return view('backend.theme.show')->withTheme($theme);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param ManageThemeRequest $request
     * @param Theme              $theme
     *
     * @return mixed
     */
    public function edit(ManageThemeRequest $request, Theme $theme)
    {
        return view('backend.theme.edit')->withTheme($theme);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateThemeRequest  $request
     * @param Theme               $theme
     *
     * @return mixed
     * @throws \App\Exceptions\GeneralException
     * @throws \Throwable
     */
    public function update(UpdateThemeRequest $request, Theme $theme)
    {
        $this->themeRepository->update($theme, $request->only(
            'title'
        ));

        // Fire update event (ThemeUpdated)
        event(new ThemeUpdated($request));

        return redirect()->route('admin.themes.index')
            ->withFlashSuccess(__('backend_themes.alerts.updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param ManageThemeRequest $request
     * @param Theme              $theme
     *
     * @return mixed
     * @throws \Exception
     */
    public function destroy(ManageThemeRequest $request, Theme $theme)
    {
        $this->themeRepository->deleteById($theme->id);

        // Fire delete event (ThemeDeleted)
        event(new ThemeDeleted($request));

        return redirect()->route('admin.themes.deleted')
            ->withFlashSuccess(__('backend_themes.alerts.deleted'));
    }

    /**
     * Permanently remove the specified resource from storage.
     *
     * @param ManageThemeRequest $request
     * @param Theme              $deletedTheme
     *
     * @return mixed
     * @throws \App\Exceptions\GeneralException
     * @throws \Throwable
     */
    public function delete(ManageThemeRequest $request, Theme $deletedTheme)
    {
        $this->themeRepository->forceDelete($deletedTheme);

        return redirect()->route('admin.themes.deleted')
            ->withFlashSuccess(__('backend_themes.alerts.deleted_permanently'));
    }

    /**
     * @param ManageThemeRequest $request
     * @param Theme              $deletedTheme
     *
     * @return mixed
     * @throws \App\Exceptions\GeneralException
     */
    public function restore(ManageThemeRequest $request, Theme $deletedTheme)
    {
        $this->themeRepository->restore($deletedTheme);

        return redirect()->route('admin.themes.index')
            ->withFlashSuccess(__('backend_themes.alerts.restored'));
    }

    /**
     * Display a listing of deleted items of the resource.
     *
     * @param ManageThemeRequest $request
     *
     * @return mixed
     */
    public function deleted(ManageThemeRequest $request)
    {
        return view('backend.theme.deleted')
            ->withthemes($this->themeRepository->getDeletedPaginated(25, 'id', 'asc'));
    }
}

resources/views/backend/theme/create.blade.php
@extends('backend.layouts.app')

@section('title', __('backend_themes.labels.management') . ' | ' . __('backend_themes.labels.create'))

@section('breadcrumb-links')
    @include('backend.theme.includes.breadcrumb-links')
@endsection

@section('content')
{{ html()->form('POST', route('admin.themes.store'))->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        @lang('backend_themes.labels.management')
                        <small class="text-muted">@lang('backend_themes.labels.create')</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <hr>

            <div class="row mt-4 mb-4">
                <div class="col">
                    <div class="form-group row">
                    {{ html()->label(__('backend_themes.validation.attributes.title'))->class('col-md-2 form-control-label')->for('title') }}

                        <div class="col-md-10">
                            {{ html()->text('title')
                                ->class('form-control')
                                ->placeholder(__('backend_themes.validation.attributes.title'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.themes.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    {{ form_submit(__('buttons.general.crud.create')) }}
                </div><!--row-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
{{ html()->closeModelForm() }}
@endsection

resources/views/backend/theme/deleted.blade.php
@extends('backend.layouts.app')

@section('title', app_name() . ' | ' . __('backend_themes.labels.management'))

@section('breadcrumb-links')
    @include('backend.theme.includes.breadcrumb-links')
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('backend_themes.labels.management') }} <small class="text-muted">{{ __('backend_themes.labels.deleted') }}</small>
                </h4>
            </div><!--col-->

            <div class="col-sm-7">
                @include('backend.theme.includes.header-buttons')
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4">
            <div class="col">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>@lang('backend_themes.table.title')</th>
                            <th>@lang('backend_themes.table.created')</th>
                            <th>@lang('backend_themes.table.deleted')</th>
                            <th>@lang('labels.general.actions')</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($themes as $theme)
                            <tr>
                                <td class="align-middle"><a href="/admin/themes/{{ $theme->id }}">{{ $theme->title }}</a></td>
                                <td class="align-middle">{!! $theme->created_at !!}</td>
                                <td class="align-middle">{{ $theme->deleted_at->diffForHumans() }}</td>
                                <td class="align-middle">{!! $theme->trashed_buttons !!}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div><!--col-->
        </div><!--row-->
        <div class="row">
            <div class="col-7">
                <div class="float-left">
                    {!! $themes->count() !!} {{ trans_choice('backend_themes.table.total', $themes->count()) }}
                </div>
            </div><!--col-->

            <div class="col-5">
                <div class="float-right">
                    {!! $themes->links() !!}
                </div>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->
</div><!--card-->
@endsection

resources/views/backend/theme/edit.blade.php
@extends('backend.layouts.app')

@section('title', __('backend_themes.labels.management') . ' | ' . __('backend_themes.labels.edit'))

@section('breadcrumb-links')
    @include('backend.theme.includes.breadcrumb-links')
@endsection

@section('content')
{{ html()->modelForm($theme, 'PATCH', route('admin.themes.update', $theme->id))->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        @lang('backend_themes.labels.management')
                        <small class="text-muted">@lang('backend_themes.labels.edit')</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <hr>

            <div class="row mt-4 mb-4">
                <div class="col">
                    <div class="form-group row">
                    {{ html()->label(__('backend_themes.validation.attributes.title'))->class('col-md-2 form-control-label')->for('title') }}

                        <div class="col-md-10">
                            {{ html()->text('title')
                                ->class('form-control')
                                ->placeholder(__('backend_themes.validation.attributes.title'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.themes.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    {{ form_submit(__('buttons.general.crud.update')) }}
                </div><!--row-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
{{ html()->closeModelForm() }}
@endsection

resources/views/backend/theme/index.blade.php
@extends('backend.layouts.app')

@section('title', app_name() . ' | ' . __('backend_themes.labels.management'))

@section('breadcrumb-links')
    @include('backend.theme.includes.breadcrumb-links')
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('backend_themes.labels.management') }} <small class="text-muted">{{ __('backend_themes.labels.active') }}</small>
                </h4>
            </div><!--col-->

            <div class="col-sm-7">
                @include('backend.theme.includes.header-buttons')
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4">
            <div class="col">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>@lang('backend_themes.table.title')</th>
                            <th>@lang('backend_themes.table.created')</th>
                            <th>@lang('backend_themes.table.last_updated')</th>
                            <th>@lang('backend_themes.table.actions')</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($themes as $theme)
                            <tr>
                                <td class="align-middle"><a href="/admin/themes/{{ $theme->id }}">{{ $theme->title }}</a></td>
                                <td class="align-middle">{!! $theme->created_at !!}</td>
                                <td class="align-middle">{{ $theme->updated_at->diffForHumans() }}</td>
                                <td class="align-middle">{!! $theme->action_buttons !!}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div><!--col-->
        </div><!--row-->
        <div class="row">
            <div class="col-7">
                <div class="float-left">
                    {!! $themes->count() !!} {{ trans_choice('backend_themes.table.total', $themes->count()) }}
                </div>
            </div><!--col-->

            <div class="col-5">
                <div class="float-right">
                    {!! $themes->links() !!}
                </div>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->
</div><!--card-->
@endsection

resources/views/backend/theme/show.blade.php
@extends('backend.layouts.app')

@section('title', __('backend_themes.labels.management') . ' | ' . __('backend_themes.labels.view'))

@section('breadcrumb-links')
    @include('backend.theme.includes.breadcrumb-links')
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    @lang('backend_themes.labels.management')
                    <small class="text-muted">@lang('backend_themes.labels.view')</small>
                </h4>
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4 mb-4">
            <div class="col">
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-expanded="true"><i class="fas fa-user"></i> @lang('backend_themes.tabs.title')</a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div class="tab-pane active" id="overview" role="tabpanel" aria-expanded="true">

                        <div class="col">
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <tr>
                                        <th>@lang('backend_themes.tabs.content.overview.title')</th>
                                        <td>{{ $theme->title }}</td>
                                    </tr>
                                </table>
                            </div><!--table-responsive-->
                        </div><!--col-->

                    </div><!--tab-->
                </div><!--tab-content-->
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->

    <div class="card-footer">
        <div class="row">
            <div class="col">
                <small class="float-right text-muted">
                    <strong>@lang('backend_themes.tabs.content.overview.created_at'):</strong> {{ timezone()->convertToLocal($theme->created_at) }} ({{ $theme->created_at->diffForHumans() }}),
                    <strong>@lang('backend_themes.tabs.content.overview.last_updated'):</strong> {{ timezone()->convertToLocal($theme->updated_at) }} ({{ $theme->updated_at->diffForHumans() }})
                    @if($theme->trashed())
                        <strong>@lang('backend_themes.tabs.content.overview.deleted_at'):</strong> {{ timezone()->convertToLocal($theme->deleted_at) }} ({{ $theme->deleted_at->diffForHumans() }})
                    @endif
                </small>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-footer-->
</div><!--card-->
@endsection